Commands:
  - '/setblock'
  - '//set'
  - '//replace'
  - '//overlay'
  - '//walls'
  - '//outline'
  - '//hcyl'
  - '//cyl'
  - '//hsphere'
  - '//sphere'
  - '//fill'
  - '//fiir'
  - '/replacenear'
  - '/removenear'
  - '//repl'
  - '//brush'
  - '//mat'
  - '//mask'
  - '//count'

List:
  - 'sl:8 # stripped_oak_log[axis=z]'
  - 'sg1 # dead_tube_coral_block'